modLoader="javafml"
loaderVersion="[36,)"
license="Creative Commons Attribution-NonCommercial 3.0"

[[mods]]
modId="superores"
version="1.0.0"
displayName="SuperOres"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="bloodieythecat"
description='''
Super Ores Is A Mod That Adds Lots of thing such as ores And some other mobs and fluids And lots of things more.
'''

[[dependencies.superores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




